### ISSUE TITLE
Jpegtran pip not working Python3

### ISSUE THREAD

**Issue by diugalde** [jbaiter/jpegtran-cffi#14]
I installed Jpegtran using pip install but it gave me the same error shown in this issue https://github.com/jbaiter/jpegtran-cffi/issues/10 

I solved the problem installing the package with pip3 install git+https://github.com/jbaiter/jpegtran-cffi.git@master but I dont like to be fetching changes from an active git repository. What can I do?

**Comment by jbaiter** [comment]
What Python 3 version are you on? I just tried to install from PyPi with 3.5 and it worked like a charm :-/ Are you sure you installed version 0.5.2 from PyPi?

**Comment by diugalde** [comment]
That was the problem, we tried using 0.5.1 because we thought that was the latest version available. I tested with 0.5.2 and it's working. Thank you.
